library:
  source-dirs: src
tests:
  ws-server-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ws-server
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- mtl
- uuid
- lens
- base >= 4.7 && < 5
- websockets
- containers
- random
name: ws-server
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/ws-server
license: BSD3
executables:
  ws-server-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random
    - containers
    - transformers
    - mtl
    - text
    - ws-server
    - uuid
description: Please see the README on GitHub at <https://github.com/githubuser/ws-server#readme>
